[package]
name = "consume-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.bench]
lto = true

[[bench]]
name = "benchmark"
harness = false

[dev-dependencies]
criterion = "0.4.0"
